server:
  port: 9091

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/project?useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/project?useSSL=false&allowPublicKeyRetrieval=true

    username: root
    password: root
  application:
    name: EMPLOYEE-SERVICE

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka



#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://host.docker.internal:8761/eureka/
#  instance:
#    hostname: localhost

